version: "3.8"
services:
  joomla:
    build:
      context: './joomla/'
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - data/:/var/www/html/joomla
      - log/:/var/log/joomla
    container_name: joomla
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    volumes:
      - db_data:/var/lib/mariadb
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: db
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MARIADB_ROOT_PASSWORD' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  frontend:
  backend:
volumes:
    db:
    data:
    log:
