version: "3.8"
services:
  joomla:
    build:
      context: './joomla/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - web_data/:/var/www/html/joomla
      - log/:/var/log/joomla
    container_name: joomla
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    container_name: mariadb
networks:
  frontend:
  backend:
volumes:
    mariadb_data:
    web_data:
    log:
